image: Visual Studio 2019

build:
  project: Manatee.Trello.sln

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

before_build:
 - nuget restore Manatee.Trello.sln
 - dotnet restore Manatee.Trello.sln
 - git submodule update --init
